Repository aswnss-m/rebootEd, pull requests merged in 2022-12, with the labels that each got.

#9 echo-echo-123
  src/assets/examples/question1.html
Labels: good first issue

#10 7-and-8 done
  src/assets/examples/images/SCTCE.jpg
  src/assets/examples/question1.html
  src/assets/examples/question7.html
  src/assets/examples/question8.html
Labels: good first issue

#12 Added Resource page
  package-lock.json
  package.json
  src/App.jsx
  src/Error.jsx
  src/Home.jsx
  src/Resource.jsx
  src/components/Navbar.jsx
  src/main.jsx
  src/styles/Navbar.css
  src/styles/Questions.css
Labels: enhancement

#13 small little touches
  src/Resource.jsx
  src/components/Footer.jsx
  src/styles/Footer.css
  src/styles/Navbar.css
Labels: enhancement

#16 Added Resource page
  src/Resource.jsx
  src/components/Navbar.jsx
  src/components/ResourceComponent.jsx
  src/styles/Questions.css
Labels: bug
